from dataclasses import dataclass
from typing import List


@dataclass
class StoreConfig:
    """Configuration for a store category URL."""
    name: str
    url: str
    tags: List[str]


STORE_CONFIG = [
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/activewear", ['Activewear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/jeans", ['Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids", ['Kids']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids/baby-and-toddler", ['Kids']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids/baby-and-toddler-baby-nb--24m", ['Kids']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids/baby-and-toddler-toddler-2t--5t", ['Kids']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids/boys", ['Kids']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids/girls", ['Kids']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids?pagefm=navigation-top+nav", ['Kids']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids/boys-bottoms", ['Kids', 'Bottoms']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids/girls-bottoms", ['Kids', 'Bottoms']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids/boys-new-arrivals", ['Kids', 'New Arrivals']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids/girls-new-arrivals", ['Kids', 'New Arrivals']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids/boys-tops", ['Kids', 'Tops']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/kids/girls-tops", ['Kids', 'Tops']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens", ['Mens']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-best-dressed-guest-weddings-and-events", ['Mens']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-cologne", ['Mens']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-coordinated-sets", ['Mens']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-spring-preview-638082107", ['Mens']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-suits", ['Mens']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-accessories", ['Mens', 'Accessories']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-accessories-activewear", ['Mens', 'Accessories', 'Activewear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-activewear", ['Mens', 'Activewear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-bottoms-activewear", ['Mens', 'Activewear', 'Bottoms']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-bottoms-athletic-jeans-jeans", ['Mens', 'Activewear', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-tops-activewear", ['Mens', 'Activewear', 'Tops']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-bottoms--1", ['Mens', 'Bottoms']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-bottoms-90s-loose-jeans-jeans", ['Mens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-bottoms-90s-straight-jeans-jeans", ['Mens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-bottoms-baggy-jeans-jeans", ['Mens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-bottoms-classic-jeans-jeans", ['Mens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-bottoms-relaxed-straight-jeans-jeans", ['Mens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-bottoms-slim-jeans-jeans", ['Mens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-bottoms-ultra-baggy-jeans-jeans", ['Mens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-jeans-bottoms", ['Mens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-bottoms-new-arrivals", ['Mens', 'Bottoms', 'New Arrivals']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-a-and-f-essentials-65294453", ['Mens', 'Casual']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-new-arrivals", ['Mens', 'New Arrivals']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-coats-and-jackets", ['Mens', 'Outerwear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-coats-and-jackets-active", ['Mens', 'Outerwear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-clearance", ['Mens', 'Sale']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-shoes", ['Mens', 'Shoes']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-swim", ['Mens', 'Swimwear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-tops--1", ['Mens', 'Tops']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-tops-new-arrivals", ['Mens', 'Tops', 'New Arrivals']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-underwear", ['Mens', 'Underwear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/mens-office-approved", ['Mens', 'Workwear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/new", ['New Arrivals']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/sale", ['Sale']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens", ['Womens']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-abercrombie-x-kemo-sabe", ['Womens']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-fragrance", ['Womens']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-spring-preview-637889935", ['Womens']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-sunday-sets-collection", ['Womens']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-accessories", ['Womens', 'Accessories']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-accessories-active", ['Womens', 'Accessories']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-activewear", ['Womens', 'Activewear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bottoms--1", ['Womens', 'Bottoms']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bottoms-active", ['Womens', 'Bottoms']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bottoms-classic-jeans-jeans", ['Womens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bottoms-curvy-jeans-jeans", ['Womens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bottoms-flare-jeans-jeans", ['Womens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bottoms-relaxed-jeans-jeans", ['Womens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bottoms-skinny-jeans-jeans", ['Womens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bottoms-straight-jeans-jeans", ['Womens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bottoms-super-skinny-jeans", ['Womens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bottoms-wide-leg-jeans-jeans", ['Womens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-jeans-bottoms", ['Womens', 'Bottoms', 'Jeans']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bottoms-new-arrivals", ['Womens', 'Bottoms', 'New Arrivals']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-a-and-f-essentials-67155128", ['Womens', 'Casual']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-dresses-and-jumpsuits", ['Womens', 'Dresses']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-dresses-and-jumpsuits-active", ['Womens', 'Dresses']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-matching-sets-dresses-and-rompers", ['Womens', 'Dresses']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-dresses-and-rompers-new-arrivals", ['Womens', 'Dresses', 'New Arrivals']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-the-a-and-f-wedding-shop", ['Womens', 'Formal']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-new-arrivals", ['Womens', 'New Arrivals']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-coats-and-jackets", ['Womens', 'Outerwear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-coats-and-jackets-active", ['Womens', 'Outerwear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-clearance", ['Womens', 'Sale']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-shoes", ['Womens', 'Shoes']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-sleep-and-intimates", ['Womens', 'Sleepwear', 'Underwear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-swim", ['Womens', 'Swimwear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-tops--1", ['Womens', 'Tops']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-tops-active", ['Womens', 'Tops']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-tops-new-arrivals", ['Womens', 'Tops', 'New Arrivals']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-bra-free-collection", ['Womens', 'Underwear']),
    StoreConfig("Abercrombie", "https://www.abercrombie.com/shop/us/womens-office-approved", ['Womens', 'Workwear']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/online-exclusives/bottoms/cat1380004", ['Bottoms']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/online-exclusives/bottoms/cat1400001", ['Bottoms']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/ae77-premium-collection/cat2490040", ['Mens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/bailey-zimmermans-faves/brg_dyn_sawymoi7ld", ['Mens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/cologne/cat90024", ['Mens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/matching-sets/cat3110070", ['Mens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/mens", ['Mens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/multipacks/brg_dyn_ksocobf7r5", ['Mens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/nfl-collection-at-ae/brg_dyn_lmj1w3tndm", ['Mens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/spring-break-shop/brg_dyn_0wa19umsr9", ['Mens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/the-collegiate-collection/brg_dyn_zef2h79c3x", ['Mens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/the-snoopy-friends-shop/brg_dyn_p6ax93e7jj", ['Mens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/accessories-socks/cat4840022", ['Mens', 'Accessories']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/activewear/cat1100008", ['Mens', 'Activewear']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/bottoms/cat10027", ['Mens', 'Bottoms']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/denim-outfitting/brg_dyn_yjkul80pvk", ['Mens', 'Jeans']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/new-arrivals/brg_dyn_fiqvft6w17", ['Mens', 'New Arrivals']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/new-this-week/cat2940013", ['Mens', 'New Arrivals']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/clearance/clrmens", ['Mens', 'Sale']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/shoes/cat4840024", ['Mens', 'Shoes']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/loungewear-pjs/cat130005", ['Mens', 'Sleepwear']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/featured/top-gifts-for-him/cat3190002", ['Mens', 'Tops']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/gift-guide/top-gifts-for-him/cat3110100", ['Mens', 'Tops']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/gift-guide/top-gifts-for-him/clrcat3110100", ['Mens', 'Tops']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/tops/cat10025", ['Mens', 'Tops']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/bestsellers/brg_dyn_q2quyg3luh", ['Mens', 'Trending']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/men/underwear/cat10032", ['Mens', 'Underwear']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/gift-guide/ae77-top-gifts/cat3130035", ['Tops']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/online-exclusives/underwear/cat1400003", ['Underwear']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/aerie-x-emily-meritt/cat3180005", ['Womens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/cat4840006", ['Womens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/clothing/cat870009", ['Womens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/featured/cat3140019", ['Womens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/real-me-collections/cat2880012", ['Womens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/undies/cat6460002", ['Womens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/ae77-premium-collection/cat2450006", ['Womens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/lifestyle-novelty-gifts/cat330001", ['Womens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/perfume-beauty/cat5450026", ['Womens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/womens", ['Womens']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/accessories-socks/cat4840018", ['Womens', 'Accessories']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/accessories-shoes/cat4130035", ['Womens', 'Accessories', 'Shoes']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/activewear/cat1090003", ['Womens', 'Activewear']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/bottoms/cat10051", ['Womens', 'Bottoms']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/dresses/cat1320034", ['Womens', 'Dresses']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/new-arrivals/brg_dyn_m7gbahcw5m", ['Womens', 'New Arrivals']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/new-this-week/cat2320001", ['Womens', 'New Arrivals']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/new-arrivals/brg_dyn_hqya6u718b", ['Womens', 'New Arrivals']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/clearance/clrcat4840006", ['Womens', 'Sale']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/clearance/clrwomens", ['Womens', 'Sale']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/shoes/cat4840020", ['Womens', 'Shoes']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/loungewear-pjs/cat730011", ['Womens', 'Sleepwear']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/swimsuits/cat7030095", ['Womens', 'Swimwear']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/new-arrivals-swimsuits/brg_dyn_wsau9tgx8a", ['Womens', 'Swimwear', 'New Arrivals']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/featured/top-gifts-for-her/cat3190001", ['Womens', 'Tops']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/gift-guide/top-gifts-for-her/cat3110099", ['Womens', 'Tops']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/tops/cat10049", ['Womens', 'Tops']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/women/bestsellers/brg_dyn_kk6r6txkiw", ['Womens', 'Trending']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/adaptive-intimates-apparel/brg_dyn_9z2w40g5in", ['Womens', 'Underwear']),
    StoreConfig("AmericanEagle", "https://www.ae.com/us/en/c/aerie/bras/cat4840012", ['Womens', 'Underwear']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/accessories", ['Accessories', 'Shoes']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/pants", ['Bottoms']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/sweatsuit-sets/sweat-pants", ['Bottoms']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/dresses", ['Dresses']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/jeans", ['Jeans']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/coats-jackets", ['Outerwear']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/coats-jackets/jackets-blazer", ['Outerwear']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/shorts", ['Shorts']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/skirts", ['Skirts']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/intimates", ['Sleepwear', 'Underwear']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/sweaters", ['Sweaters']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/shirts-blouses", ['Tops']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/tops", ['Tops']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/sweatsuit-sets/sweat-shirts", ['Tops', 'Sweaters']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/tshirts", ['Tops', 'T-Shirts']),
    StoreConfig("Aritzia", "https://www.aritzia.com/us/en/clothing/womens-workout-clothes", ['Womens', 'Activewear']),
]
